### ISSUE TITLE
Set up TypeScript

### ISSUE THREAD

**Issue by ateliereven** [Mityaalim-App/Mityaalim-Server#15]
- npm i -D typescript @types/express @types/node @types/cors  concurrently nodemon

- Generate tsconfig.json : npx tsc --init

- Add configuration to tsconfig.json: 
{
  "compilerOptions": {
    "outDir": "./dist"
    // rest options remain same
  }
}

- Add script to package.json: 
"scripts": {
    "build": "npx tsc",
    "start": "tsc --watch --preserveWatchOutput",
    "prepublishOnly": "tsc",
    "dev": "concurrently \"npx tsc --watch\" \"nodemon -q dist/index.js\"" (to start up the server for development)
  }

**Comment by YarinLevi5** [comment]
Fixed to dist folder
